from deep_learning_dentistry.data_curation.data_processing.bleeding_processor import curate_clean_transform_process_save_bleeding
from deep_learning_dentistry.data_curation.data_processing.chart_endo_processor import curate_clean_transform_process_save_endo
from deep_learning_dentistry.data_curation.data_processing.chart_general_processor import curate_clean_transform_process_save_chart_general
from deep_learning_dentistry.data_curation.data_processing.chart_restorative_processor import curate_clean_transform_process_save_restore
from deep_learning_dentistry.data_curation.data_processing.demographics_data_processor import curate_clean_transform_process_save_demographics_data
from deep_learning_dentistry.data_curation.data_processing.furcation_processor import curate_clean_transform_process_save_furcation
from deep_learning_dentistry.data_curation.data_processing.index_processor import curate_clean_transform_process_save_index
from deep_learning_dentistry.data_curation.data_processing.mag_processor import curate_clean_transform_process_save_mag
from deep_learning_dentistry.data_curation.data_processing.mobility_processor import curate_clean_transform_process_save_mobility
from deep_learning_dentistry.data_curation.data_processing.pockets_processor import curate_clean_transform_process_save_pockets
from deep_learning_dentistry.data_curation.data_processing.recessions_processor import curate_clean_transform_process_save_recessions
from deep_learning_dentistry.data_curation.data_processing.suppuration_processor import curate_clean_transform_process_save_suppuration

def curate_and_clean_and_save_all_data():
    curate_clean_transform_process_save_bleeding()
    curate_clean_transform_process_save_endo()
    curate_clean_transform_process_save_chart_general()
    curate_clean_transform_process_save_restore()
    curate_clean_transform_process_save_demographics_data()
    curate_clean_transform_process_save_furcation()
    curate_clean_transform_process_save_index()
    curate_clean_transform_process_save_mag()
    curate_clean_transform_process_save_mobility()
    curate_clean_transform_process_save_pockets()
    curate_clean_transform_process_save_recessions()
    curate_clean_transform_process_save_suppuration()

if __name__ == '__main__':
    curate_and_clean_and_save_all_data()